/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class UserDoesNotExist extends errors.AmethystError {
    constructor() {
        super({
            statusCode: 404,
        });
        Object.setPrototypeOf(this, UserDoesNotExist.prototype);
    }
}
