/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../core";
import * as Amethyst from "../../..";
import * as serializers from "../../../../serialization";
import urlJoin from "url-join";
import * as errors from "../../../../errors";

export declare namespace Applications {
    interface Options {
        environment: core.Supplier<string>;
    }
}

export class Applications {
    constructor(protected readonly _options: Applications.Options) {}

    /**
     * Manage a player's application
     */
    public async manageApplication(
        request: Amethyst.ManageApplicationRequest
    ): Promise<Amethyst.ApplicationManageStatus> {
        const _response = await core.fetcher({
            url: urlJoin(await core.Supplier.get(this._options.environment), "/applications/manage-application"),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "@tristansmp/amethyst",
                "X-Fern-SDK-Version": "0.0.21",
            },
            contentType: "application/json",
            body: await serializers.ManageApplicationRequest.jsonOrThrow(request, { unrecognizedObjectKeys: "strip" }),
            timeoutMs: 60000,
        });
        if (_response.ok) {
            return await serializers.ApplicationManageStatus.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AmethystError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AmethystError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.AmethystTimeoutError();
            case "unknown":
                throw new errors.AmethystError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
