/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ApplicationStatus = "NotMember" | "Member";

export const ApplicationStatus = {
    NotMember: "NotMember",
    Member: "Member",
} as const;
