/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Amethyst from "../../../../api";
import * as core from "../../../../core";

export const ApplicationStatus: core.serialization.Schema<
    serializers.ApplicationStatus.Raw,
    Amethyst.ApplicationStatus
> = core.serialization.enum_(["NotMember", "Member"]);

export declare namespace ApplicationStatus {
    type Raw = "NotMember" | "Member";
}
