/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Amethyst from "../../../../api";
import * as core from "../../../../core";

export const PlayerId: core.serialization.Schema<serializers.PlayerId.Raw, Amethyst.PlayerId> =
    core.serialization.string();

export declare namespace PlayerId {
    type Raw = string;
}
