/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Amethyst from "../../../../api";
import * as core from "../../../../core";

export const TaskResult: core.serialization.ObjectSchema<serializers.TaskResult.Raw, Amethyst.TaskResult> =
    core.serialization.object({
        success: core.serialization.boolean(),
        error: core.serialization.string().optional(),
    });

export declare namespace TaskResult {
    interface Raw {
        success: boolean;
        error?: string | null;
    }
}
