/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Applications } from "./api/resources/applications/client/Client";

export declare namespace AmethystClient {
    interface Options {
        environment: core.Supplier<string>;
    }
}

export class AmethystClient {
    constructor(protected readonly _options: AmethystClient.Options) {}

    protected _applications: Applications | undefined;

    public get applications(): Applications {
        return (this._applications ??= new Applications(this._options));
    }
}
