/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AmethystEnvironment = {
    Production: "https://ame.tristansmp.com",
    Development: "http://localhost:8080",
} as const;

export type AmethystEnvironment = typeof AmethystEnvironment.Production | typeof AmethystEnvironment.Development;
